version: "3"
services:
  3m:
    image: docker.io/whateverany/3m:0.0.1
    working_dir: /opt/3m
    volumes:
      - .:/opt/3m
      - ${_DOCKER_HOME:-.docker}:/root/.docker
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ${ENVFILE:-.env}

